
import React from 'react';
import { 
  Utensils,
  Car,
  ShoppingBag,
  Home,
  Zap,
  Coffee,
  Briefcase,
  TrendingUp,
  Gift,
  ArrowDownLeft,
  Smartphone,
  HeartPulse,
  Plane,
  Gamepad2,
  GraduationCap,
  Hammer,
  Banknote,
  Coins,
  PawPrint,
  Tv,
  Wifi,
  Baby,
  ShieldCheck,
  Book,
  PenTool,
  Heart,
  Theater,
  Beer,
  Music,
  Pizza,
  Dumbbell,
  Cpu,
  GlassWater,
  Soup,
  Shirt,
  Scissors,
  Clapperboard,
  HardHat,
  Stethoscope,
  Umbrella,
  Camera,
  Compass,
  Bus,
  Train,
  Bike,
  Wrench,
  Flame,
  Cloud,
  Film,
  Moon,
  Sun,
  Palette,
  Mic2,
  Radio,
  Gamepad,
  Trophy,
  Activity,
  Trees,
  CloudRain,
  Anchor,
  Tag
} from 'lucide-react';

export const ICON_MAP: Record<string, React.ReactNode> = {
  Utensils: <Utensils size={18} />,
  Pizza: <Pizza size={18} />,
  Soup: <Soup size={18} />,
  Coffee: <Coffee size={18} />,
  Beer: <Beer size={18} />,
  GlassWater: <GlassWater size={18} />,
  Car: <Car size={18} />,
  Bus: <Bus size={18} />,
  Train: <Train size={18} />,
  Bicycle: <Bike size={18} />,
  Plane: <Plane size={18} />,
  Compass: <Compass size={18} />,
  ShoppingBag: <ShoppingBag size={18} />,
  Shirt: <Shirt size={18} />,
  Scissors: <Scissors size={18} />,
  Home: <Home size={18} />,
  Zap: <Zap size={18} />,
  Hammer: <Hammer size={18} />,
  Wrench: <Wrench size={18} />,
  Briefcase: <Briefcase size={18} />,
  TrendingUp: <TrendingUp size={18} />,
  Gift: <Gift size={18} />,
  Smartphone: <Smartphone size={18} />,
  Wifi: <Wifi size={18} />,
  Tv: <Tv size={18} />,
  Gamepad: <Gamepad size={18} />,
  Clapperboard: <Clapperboard size={18} />,
  Film: <Film size={18} />,
  Theater: <Theater size={18} />,
  Palette: <Palette size={18} />,
  Music: <Music size={18} />,
  Mic2: <Mic2 size={18} />,
  Radio: <Radio size={18} />,
  HeartPulse: <HeartPulse size={18} />,
  Heart: <Heart size={18} />,
  Activity: <Activity size={18} />,
  Stethoscope: <Stethoscope size={18} />,
  GraduationCap: <GraduationCap size={18} />,
  Book: <Book size={18} />,
  Banknote: <Banknote size={18} />,
  Coins: <Coins size={18} />,
  Trophy: <Trophy size={18} />,
  PawPrint: <PawPrint size={18} />,
  Baby: <Baby size={18} />,
  ShieldCheck: <ShieldCheck size={18} />,
  PenTool: <PenTool size={18} />,
  Dumbbell: <Dumbbell size={18} />,
  Cpu: <Cpu size={18} />,
  HardHat: <HardHat size={18} />,
  Umbrella: <Umbrella size={18} />,
  Camera: <Camera size={18} />,
  Flame: <Flame size={18} />,
  Moon: <Moon size={18} />,
  Sun: <Sun size={18} />,
  Cloud: <Cloud size={18} />,
  CloudRain: <CloudRain size={18} />,
  Trees: <Trees size={18} />,
  Anchor: <Anchor size={18} />,
  Tag: <Tag size={18} />,
  ArrowDownLeft: <ArrowDownLeft size={18} />
};

export const CATEGORIES = [
  { name: 'Alimentación', icon: 'Utensils', color: '#f87171' },
  { name: 'Transporte', icon: 'Car', color: '#60a5fa' },
  { name: 'Compras', icon: 'ShoppingBag', color: '#fbbf24' },
  { name: 'Vivienda', icon: 'Home', color: '#818cf8' },
  { name: 'Suministros', icon: 'Zap', color: '#facc15' },
  { name: 'Ocio', icon: 'Coffee', color: '#f472b6' },
  { name: 'Salud', icon: 'HeartPulse', color: '#34d399' },
  { name: 'Viajes', icon: 'Plane', color: '#2dd4bf' },
  { name: 'Educación', icon: 'GraduationCap', color: '#a78bfa' },
  { name: 'Suscripciones', icon: 'Tv', color: '#4ade80' },
  { name: 'Mascotas', icon: 'PawPrint', color: '#fb923c' }
];

export const INCOME_CATEGORIES = [
  { name: 'Nómina', icon: 'Briefcase', color: '#10b981' },
  { name: 'Inversiones', icon: 'TrendingUp', color: '#8b5cf6' },
  { name: 'Regalos', icon: 'Gift', color: '#ec4899' },
  { name: 'Ventas', icon: 'ShoppingBag', color: '#f59e0b' },
  { name: 'Premios', icon: 'Coins', color: '#facc15' },
  { name: 'Otros Ingresos', icon: 'Banknote', color: '#64748b' },
];

export const BUDGET_PRESET_COLORS = [
  '#ef4444', '#f97316', '#f59e0b', '#eab308', '#84cc16', '#22c55e', 
  '#10b981', '#06b6d4', '#3b82f6', '#6366f1', '#8b5cf6', '#a855f7', 
  '#d946ef', '#ec4899', '#f43f5e', '#64748b', '#475569', '#1e293b'
];

export const INITIAL_DATA = {
  accounts: [
    { id: 'acc1', name: 'Banco Principal', type: 'Bank', initialBalance: 1200, currentBalance: 1200, color: '#3b82f6', emoji: '🏦' },
    { id: 'acc2', name: 'Efectivo', type: 'Cash', initialBalance: 150, currentBalance: 150, color: '#10b981', emoji: '💵' }
  ],
  savings: [
    { id: 'sav1', name: 'Fondo Emergencia', currentAmount: 3000, isInvestment: false, color: '#f59e0b', emoji: '🛡️' },
    { id: 'sav2', name: 'Inversión S&P 500', currentAmount: 1500, isInvestment: true, growthRate: 8, color: '#8b5cf6', emoji: '📈' }
  ],
  refunds: [],
  transactions: [],
  budgets: [
    { id: 'b1', category: 'Alimentación', limit: 200, icon: 'Utensils', spent: 0, type: 'expense', color: '#f87171' },
    { id: 'b2', category: 'Ocio', limit: 100, icon: 'Coffee', spent: 0, type: 'expense', color: '#f472b6' },
    { id: 'b3', category: 'Nómina', limit: 2000, icon: 'Briefcase', spent: 0, type: 'income', color: '#10b981' }
  ],
  challenges: [
    { id: 'ch1', title: 'Limitar gastos en Ocio', target: 50, current: 0, type: 'spending_limit', category: 'Ocio', completed: false },
    { id: 'ch2', title: 'Meta de ahorro mensual', target: 500, current: 0, type: 'savings_goal', completed: false }
  ],
  extraSavings: [],
  manualContributions: {},
  currentDate: new Date().toISOString().substring(0, 7),
  viewMode: 'month',
  dashboardLayout: ['balance', 'challenges', 'savings', 'chart', 'accounts', 'budget'],
  chatHistory: [],
  chatLastDate: ''
};
